# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            CB
tagline:          'Carlos Benavidez Repository'
description:      'Open Source Repository of Web Accessibility Evaluation Tools.'
url:              http://carlosbenavidez.tk
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://carlosbenavidez.tk
