# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            CB
tagline:          'Carlos Benavidez Repository'
description:      'Open Source Repository of Web Accessibility Evaluation Tools.'
url:              http://www.carlosbenavidez.tk
baseurl:          http://www.carlosbenavidez.tk/

author:
  name:           'Jorge Fernandes'
  url:            https://twitter.com/91408

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://unidade-acesso/unidade-acesso.github.io
